services:
  krisiko:
    build: .
    container_name: krisiko
    ports:
      - "3080:80"
    environment:
      # silent | error | warn | info | debug
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      PORT: "80"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
        tag: "{{.Name}}"
